package autorize.model;

public enum InterceptionFilterType {
  SCOPE_ONLY,
  URL_CONTAINS,
  URL_REGEX,
  URL_NOT_CONTAINS,
  URL_NOT_REGEX,
  REQ_BODY_CONTAINS,
  REQ_BODY_REGEX,
  REQ_BODY_NOT_CONTAINS,
  REQ_BODY_NOT_REGEX,
  RES_BODY_CONTAINS,
  RES_BODY_REGEX,
  RES_BODY_NOT_CONTAINS,
  RES_BODY_NOT_REGEX,
  REQ_HEADER_CONTAINS,
  REQ_HEADER_NOT_CONTAINS,
  RES_HEADER_CONTAINS,
  RES_HEADER_NOT_CONTAINS,
  ONLY_METHODS,
  IGNORE_METHODS,
  IGNORE_OPTIONS,
  IGNORE_PROXY,
  IGNORE_TARGET,
  DROP_PROXY_PORTS
}
